import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {createWalletClient,custom,isAddress,type Address,type EIP1193Provider} from 'viem';
import {NETWORK} from './chain';
export type ProviderDetail={info:{uuid:string;name:string;icon:string;rdns:string};provider:EIP1193Provider & {on?:(e:string,fn:(arg:any)=>void)=>void;removeListener?:(e:string,fn:(arg:any)=>void)=>void}};
type WalletState={providers:ProviderDetail[];selected:ProviderDetail|null;address:Address|null;chainId:number|null;error:string;busy:boolean;connect:(p:ProviderDetail)=>Promise<void>;disconnect:()=>void;switchChain:()=>Promise<void>;changeAccount:()=>Promise<void>;wallet:ReturnType<typeof createWalletClient>|null;};
const Context=createContext<WalletState|null>(null);
export function WalletProvider({children}:{children:ReactNode}){
 const [providers,setProviders]=useState<ProviderDetail[]>([]),[selected,setSelected]=useState<ProviderDetail|null>(null),[address,setAddress]=useState<Address|null>(null),[chainId,setChain]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const generation=useRef(0);
 const disconnect=()=>{generation.current++;setSelected(null);setAddress(null);setChain(null);setError('');setBusy(false);};
 useEffect(()=>{const announce=(event:Event)=>{const d=(event as CustomEvent<ProviderDetail>).detail;if(d?.info?.uuid&&typeof d.info.name==='string'&&typeof d.provider?.request==='function')setProviders(p=>p.some(v=>v.info.uuid===d.info.uuid)?p:[...p,d]);};window.addEventListener('eip6963:announceProvider',announce);window.dispatchEvent(new Event('eip6963:requestProvider'));return()=>window.removeEventListener('eip6963:announceProvider',announce);},[]);
 useEffect(()=>{if(!selected)return;const accounts=(v:string[])=>{if(v?.[0]&&isAddress(v[0]))setAddress(v[0] as Address);else disconnect();},chain=(v:string)=>{const n=parseInt(v,16);setChain(Number.isSafeInteger(n)?n:null);};selected.provider.on?.('accountsChanged',accounts);selected.provider.on?.('chainChanged',chain);selected.provider.on?.('disconnect',disconnect);return()=>{selected.provider.removeListener?.('accountsChanged',accounts);selected.provider.removeListener?.('chainChanged',chain);selected.provider.removeListener?.('disconnect',disconnect);};},[selected]);
 const connect=async(p:ProviderDetail)=>{const run=++generation.current;setBusy(true);setError('');try{const accounts=await p.provider.request({method:'eth_requestAccounts'});if(!accounts[0]||!isAddress(accounts[0]))throw new Error('No account was shared by this wallet.');const chain=parseInt(await p.provider.request({method:'eth_chainId'}),16);if(run!==generation.current)return;setAddress(accounts[0]);setChain(chain);setSelected(p);}catch(e){if(run===generation.current)setError(e instanceof Error?e.message:'Connection declined.');}finally{if(run===generation.current)setBusy(false);}};
 const changeAccount=async()=>{if(!selected)return;const run=++generation.current;setBusy(true);setError('');try{await selected.provider.request({method:'wallet_requestPermissions',params:[{eth_accounts:{}}]});const accounts=await selected.provider.request({method:'eth_accounts'});if(run!==generation.current)return;if(!accounts[0]||!isAddress(accounts[0])){disconnect();return;}setAddress(accounts[0]);}catch(e){if(run===generation.current)setError((e as {code?:number}).code===4200?'This extension does not support an account picker. Change the selected account inside the extension.':e instanceof Error?e.message:'Account change declined.');}finally{if(run===generation.current)setBusy(false);}};
 const switchChain=async()=>{if(!selected)return;const run=++generation.current;setBusy(true);setError('');try{try{await selected.provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x1237'}]});}catch(e){if((e as {code:number}).code!==4902)throw e;await selected.provider.request({method:'wallet_addEthereumChain',params:[{chainId:'0x1237',chainName:NETWORK.name,nativeCurrency:NETWORK.nativeCurrency,rpcUrls:[...NETWORK.rpcUrls.default.http],blockExplorerUrls:[NETWORK.blockExplorers!.default.url]}]});}const chain=parseInt(await selected.provider.request({method:'eth_chainId'}),16);if(run===generation.current)setChain(chain);}catch(e){if(run===generation.current)setError(e instanceof Error?e.message:'Network switch declined.');}finally{if(run===generation.current)setBusy(false);}};
 return <Context.Provider value={{providers,selected,address,chainId,error,busy,connect,disconnect,switchChain,changeAccount,wallet:selected?createWalletClient({chain:NETWORK,transport:custom(selected.provider)}):null}}>{children}</Context.Provider>;
}
export function useWallet(){const c=useContext(Context);if(!c)throw new Error('Wallet context missing');return c;}
