import {useEffect,useRef,useState} from 'react';
import {AudioLines,Check,Code2,FileImage,Mic,Square,Trash2,Upload,LoaderCircle} from 'lucide-react';
import {bytesLabel,externalReferences,isolatedHtml,makeAsset,optimizeImage,type AssetKind,type ContentAsset} from '../lib/assets';
export function useAssetUrl(asset?:ContentAsset){const [entry,setEntry]=useState<{asset:ContentAsset;url:string}|null>(null);useEffect(()=>{if(!asset){setEntry(null);return;}const next=URL.createObjectURL(new Blob([Uint8Array.from(asset.bytes)],{type:asset.mime}));setEntry({asset,url:next});return()=>URL.revokeObjectURL(next);},[asset]);return entry?.asset===asset?entry?.url||'':'';}
const icons={image:FileImage,audio:AudioLines,website:Code2};
const titles={image:'Image or GIF animation',audio:'A sound of its own',website:'A website that stays'};
const accepts={image:'image/png,image/jpeg,image/webp,image/gif',audio:'audio/mpeg,audio/mp4,audio/wav,audio/ogg,audio/webm',website:'.html,.htm'};
export function AssetEditor({kind,asset,onChange}:{kind:AssetKind;asset?:ContentAsset;onChange:(a:ContentAsset|undefined)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[dimension,setDimension]=useState(256),[recording,setRecording]=useState(false),[html,setHtml]=useState(''),[editing,setEditing]=useState(false);
 const input=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true);const url=useAssetUrl(asset),Icon=icons[kind];
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(timer.current)clearTimeout(timer.current);recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 const receive=async(file?:File)=>{if(!file)return;setBusy(true);setError('');try{const a=kind==='image'?await optimizeImage(file,dimension):await makeAsset(kind,file.name,file.type,new Uint8Array(await file.arrayBuffer()));if(alive.current)onChange(a);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 async function record(){setError('');try{if(!navigator.mediaDevices||!window.MediaRecorder)throw new Error('Recording is unavailable in this browser. Upload an audio file instead.');stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(x=>MediaRecorder.isTypeSupported(x));const r=new MediaRecorder(stream.current,{...(mime?{mimeType:mime}:{}),audioBitsPerSecond:24000});const chunks:Blob[]=[];r.ondataavailable=e=>e.data.size&&chunks.push(e.data);r.onstop=async()=>{stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);if(!alive.current)return;setRecording(false);try{const blob=new Blob(chunks,{type:r.mimeType});onChange(await makeAsset('audio','carve-recording',r.mimeType,new Uint8Array(await blob.arrayBuffer())));}catch(e){setError((e as Error).message);}};recorder.current=r;r.start();setRecording(true);timer.current=setTimeout(()=>r.state==='recording'&&r.stop(),5000);}catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError((e as Error).message);}}
 const websiteText=asset&&kind==='website'?new TextDecoder().decode(asset.bytes):'';const refs=externalReferences(websiteText);
 return <section className={`asset-editor asset-${kind}`}>
 <div className="asset-heading"><div><Icon size={18}/><h3>{titles[kind]}</h3></div><span className={`tiny-tag ${asset?'good':''}`}>{asset?<><Check size={12}/>Prepared</>:'Optional'}</span></div>
 <input ref={input} type="file" accept={accepts[kind]} aria-label={`Upload ${kind}`} className="visually-hidden" onChange={e=>{receive(e.target.files?.[0]);e.target.value='';}}/>
 {!asset?<button className="upload-zone" disabled={busy} onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();receive(e.dataTransfer.files[0]);}}>{busy?<LoaderCircle className="spin"/>:<Upload size={22}/>}<strong>{busy?'Preparing your file…':`Drop ${kind==='image'?'an image':kind==='audio'?'a sound':'an HTML file'} here`}</strong><span>or click to browse</span><small>{kind==='image'?'PNG, JPG, WebP or GIF':kind==='audio'?'MP3, M4A, WAV, OGG or WebM':'Self-contained HTML · embedded assets'}</small></button>:<div className="asset-ready">{kind==='image'&&url&&<img className="asset-thumbnail" src={url} alt="Your token image"/>}{kind==='audio'&&url&&<audio controls src={url} preload="metadata"/>}{kind==='website'&&<iframe title="Isolated website preview" sandbox="allow-scripts" srcDoc={isolatedHtml(websiteText)}/>}<div className="file-meta"><span title={asset.name}>{asset.name}</span><strong>{bytesLabel(asset.bytes.length)}</strong><button className="icon-button" aria-label={`Remove ${kind}`} onClick={()=>onChange(undefined)}><Trash2 size={15}/></button></div>{asset.originalBytes>asset.bytes.length&&<p className="saved-bytes">{Math.round((1-asset.bytes.length/asset.originalBytes)*100)}% smaller · prepared locally</p>}</div>}
 {kind==='image'&&<div className="asset-options"><span>Image preparation</span><div className="segmented">{[128,256,512].map(s=><button key={s} className={s===dimension?'selected':''} onClick={()=>setDimension(s)} aria-pressed={s===dimension}>{s}px</button>)}</div><p>GIFs are automatically reduced in size and colours while preserving animation. Preview the result before launch. Maximum prepared size: 1 MB; larger assets require chunked uploads.</p></div>}
 {kind==='audio'&&!asset&&<button className={`secondary record ${recording?'recording':''}`} disabled={busy} onClick={recording?()=>recorder.current?.stop():record}>{recording?<Square size={15}/>:<Mic size={15}/>} {recording?'Stop recording':'Record up to 5 seconds'}</button>}
 {kind==='website'&&<><button className="text-link editor-toggle" onClick={()=>{setHtml(websiteText);setEditing(!editing);}}><Code2 size={15}/>{editing?'Close editor':'Write HTML instead'}</button>{editing&&<div className="html-editor"><textarea spellCheck={false} aria-label="Website HTML" placeholder="<!doctype html>\n<html>…</html>" value={html} onChange={e=>setHtml(e.target.value)}/><button className="secondary" onClick={async()=>{try{onChange(await makeAsset('website','index.html','text/html',new TextEncoder().encode(html)));setEditing(false);setError('');}catch(e){setError((e as Error).message);}}}>Prepare website</button></div>}{refs.length>0&&<p className="warning">This page references {refs.length} external or relative resource{refs.length!==1?'s':''}. Embed them as data URIs; external resources are blocked in the isolated preview and are not inscribed.</p>}<p className="asset-note">Isolated preview. No wallet access or external network requests.</p></>}
 {error&&<p className="error" role="alert">{error}</p>}
 </section>;
}
