import {BookOpen,ArrowUpRight,Download,ShieldCheck} from 'lucide-react';
import {DEPLOYMENT} from '../lib/chain';
const scan='https://robinhoodchain.blockscout.com';
export function DocsPage(){return <>
 <div className="page-heading compact"><div><div className="eyebrow">CARVE DOCUMENTATION</div><h1>Verify. Don’t just trust.</h1><p>Trace a token’s image, sound and website back to Robinhood Chain.</p></div><BookOpen size={32}/></div>
 <div className="docs-grid"><article className="panel prose verification-docs">
 <h2>What “onchain” means here</h2><p>Carve stores the actual prepared file bytes in immutable contract bytecode. Each token points to content records for its image, audio and website. Each record identifies the file type, encoding, length, ordered storage addresses and chunk hashes. A hash or external link alone is not the file.</p>
 <h2>Quick verification · no wallet needed</h2><ol><li>Open <a href="#/explore">Explore</a> and enter the token’s contract address on Robinhood Chain.</li><li>Choose <strong>Verify inscription</strong>. Carve reads the stored bytes from the public RPC and checks each chunk hash and the complete content record.</li><li>View the reconstructed image, play the sound or open the isolated website preview. Absent media is not an error: a launch may include any one, two or all three types.</li><li>Download the original bytes and proof. <strong>Copy media data URL</strong> creates a self-contained URL from those verified bytes—not a link to an image host.</li></ol>
 <p>Paste a copied <code>data:</code> URL directly into a browser’s address bar. Support and URL-length limits vary; downloading the original file is the reliable fallback. HTML may contain arbitrary scripts: prefer Carve’s isolated preview or the independent verifier rather than opening unknown HTML unrestricted.</p>
 <h2>Check directly on the explorer</h2><ol><li>Open the token address on Robinhood’s explorer and select <strong>Contract → Read contract</strong>. Check <code>contentRegistry()</code>, <code>imageRoot()</code>, <code>audioRoot()</code> and <code>websiteRoot()</code>. An all-zero root means that media type is absent.</li><li>Open the returned registry address. In <code>getContent(bytes32)</code>, paste a nonzero root. Record <code>mimeType</code>, <code>encoding</code>, <code>byteLength</code>, <code>pointers</code> and <code>chunkHashes</code>.</li><li>Use <code>read(bytes32)</code> with that root to read the stored bytes. For larger files, use <code>readChunk(address)</code> for each pointer in the exact recorded order.</li><li>Each pointer’s deployed bytecode begins with <code>00</code>, followed by its file bytes. Remove only that leading STOP byte when reading raw bytecode—not when using <code>readChunk</code>, which already removes it.</li><li>Join the chunks in order. Verify each Keccak-256 hash and total encoded length. If encoding is <code>gzip</code>, decompress after verifying the stored bytes. For <code>identity</code>, those bytes already are the file.</li></ol>
 <p>The explorer’s Read panel needs the contract ABI/source information to be indexed. If it is unavailable, use the independent verifier below; public RPC reads do not require a wallet or Carve’s server. A content root is not a browser URL. The token currently does not expose a <code>tokenURI()</code> getter or force the explorer to render custom ERC-20 media automatically.</p>
 <h2>Verify without Carve’s website</h2><p>Download and keep the standalone verifier. Open the HTML file locally, enter a token address and verify from the public Robinhood RPC. Its code and libraries are bundled in the file: no Carve backend, CDN script, account or wallet is required. An internet connection to the public RPC is still needed; it is not an offline blockchain.</p><a className="secondary" href="/carve-verifier.html" download><Download size={16}/>Download independent verifier</a>
 <details><summary>Technical content-root calculation</summary><p>After validating the chunks, the content root must equal:</p><pre><code>{'keccak256(abi.encode(\n  uint8(1), mimeType, encoding,\n  uint256(encodedByteLength),\n  orderedPointers, orderedChunkHashes\n))'}</code></pre><p>Field types are <code>uint8,string,string,uint256,address[],bytes32[]</code>. Encoded byte length is measured before gzip decompression. Root validation checks the integrity of the onchain record, not the uploader’s identity or investment claims.</p></details>
 <h2>What verification proves—and does not</h2><p>It proves which bytes are attached to a token and whether they match their stored commitments. It does not prove that uploaded claims are true, that a file is safe, that every browser supports its codec, or that a token will retain value. Missing, malformed or unavailable data must produce an error, not a “verified” preview.</p><p>Image, sound and website playback are checked separately from byte integrity. Audio starts after a user action where required by the browser. Websites run in a sandbox without wallet access. Public RPCs and explorer indexing may be delayed or unavailable.</p>
 <h2>Creating an inscription</h2><p>Prepare at least one image, sound or self-contained HTML file in Create. You can include all three. Each prepared file is limited to 1 MB; storage is split into chunks up to 20 KiB. Review the prepared bytes, fees and permanent settings before approving. Confirmed uploads can be resumed from the same browser draft and wallet.</p><p>Once published, the token’s stored media references cannot be edited. Only publish content you are entitled to share. Creating a token and its files costs real gas, even if no one trades it afterward.</p><a className="text-link" href="#/protocol">Read trading, fee and liquidity mechanics <ArrowUpRight size={15}/></a>
 </article><aside className="panel readiness"><h2><ShieldCheck size={20}/> Public proof points</h2><p>Network: Robinhood Chain · 4663. Compare addresses rather than names or logos.</p>{(['registry','factory','engine','router'] as const).map(name=>DEPLOYMENT[name]&&<a key={name} href={scan+'/address/'+DEPLOYMENT[name]+'?tab=contract'} target="_blank" rel="noreferrer">{name[0].toUpperCase()+name.slice(1)} contract <ArrowUpRight size={14}/></a>)}
 {DEPLOYMENT.deploymentTx&&<a href={scan+'/tx/'+DEPLOYMENT.deploymentTx} target="_blank" rel="noreferrer">Launchpad deployment receipt <ArrowUpRight size={14}/></a>}
 <p>{DEPLOYMENT.status==='verified'?'Deployment bytecode and immutable settings were checked against the compiled build.':'The retained content registry is live; the immediate-trading factory is awaiting deployment verification.'} Explorer source-verification status is separate; a completed deployment is not an independent security audit.</p><p>Never enter a seed phrase or approve a transaction to read an inscription.</p></aside></div>
 </>;}
