import {useRef,useState,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowRight,AudioLines,Check,Download,FileImage,Globe,Info,ShieldCheck,X} from 'lucide-react';
import {useWallet} from '../lib/wallet';
import {bytesLabel,download,exportDraft,isolatedHtml,planAssets,validateDraft,type AssetKind,type Draft} from '../lib/assets';
import {AssetEditor,useAssetUrl} from './AssetEditor';
import {DEPLOYMENT,short} from '../lib/chain';
import {sampleGifURL,sampleGifStillURL} from '../lib/sample-gif';
import {v3LaunchPlan} from '../lib/v3-launch-plan';
import {readCapsuleHTML} from '../lib/agent-capsule';
import {LaunchAction} from './LaunchAction';
import {buddyAssets} from './buddy-runtime';

function Status({children}:{children:ReactNode}){return <span className="status-tag">{children}</span>;}
function SectionTitle({number,title,description}:{number:string;title:string;description?:string}){return <div className="section-title"><span className="section-number">{number}</span><div><h2>{title}</h2>{description&&<p>{description}</p>}</div></div>;}

function Review({draft}:{draft:Draft}){
 const [open,setOpen]=useState(false),w=useWallet(),plan=v3LaunchPlan(draft),issues=validateDraft(draft);
 return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className="primary full">Review inscription <ArrowRight size={18}/></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content review-dialog"><Dialog.Title>Review your inscription</Dialog.Title><Dialog.Description>Check your prepared files before any permanent onchain upload.</Dialog.Description><Dialog.Close className="icon-button dialog-close" aria-label="Close review"><X/></Dialog.Close>
 <dl className="review-details"><div><dt>Token</dt><dd>{draft.name||'Name needed'} · ${draft.symbol||'TICKER'}</dd></div><div><dt>Network</dt><dd>Robinhood Chain · 4663</dd></div><div><dt>Prepared media</dt><dd>{plan.files} files · {bytesLabel(plan.bytes)}</dd></div><div><dt>Wallet approvals</dt><dd>{plan.inline?([4,5].includes(DEPLOYMENT.curveVersion||0)?'1 · media + token + curve':'1 · media + token + pool'):`Up to ${plan.transactions} · resumable uploads`}</dd></div><div><dt>Initial buy</dt><dd>{draft.initialBuy||'0'} ETH</dd></div><div><dt>Connected wallet</dt><dd>{w.address?short(w.address):'Not connected'}</dd></div><div><dt>Launch fee</dt><dd>0.0005 ETH + storage & transaction gas</dd></div></dl>
 {issues.length>0&&<div className="warning"><strong>Still needed</strong><ul>{issues.map(x=><li key={x}>{x}</li>)}</ul></div>}
 <LaunchAction key={w.address+':'+w.selected?.info.uuid+':'+w.chainId} draft={draft}/>
 <button className="primary full" onClick={()=>download((draft.symbol||'carve')+'-draft.json',exportDraft(draft))}><Download size={17}/>Download prepared draft</button>
 <p className="muted">Published bytes are permanent. Only upload media you have permission to use. Confirmed chunks are reused when you resume the same draft.</p>
 </Dialog.Content></Dialog.Portal></Dialog.Root>;
}

export function Studio({draft,setDraft,saved}:{draft:Draft;setDraft:(d:Draft)=>void;saved:string}){
 const currentDraft=useRef(draft);currentDraft.current=draft;
 const [preview,setPreview]=useState<'image'|'website'|'sample'>('image');const plan=planAssets(draft.assets),url=useAssetUrl(draft.assets.image),audio=useAssetUrl(draft.assets.audio);
 const update=(key:keyof Draft,value:string|boolean)=>setDraft({...draft,[key]:value,updatedAt:Date.now()});
 return <><div className="page-heading studio-heading"><div><div className="eyebrow">CARVE / ON ROBINHOOD CHAIN</div><h1>Launch tokens.<br/><em>Preserve creativity.</em></h1><p>Images. Sound. Websites. Permanently onchain.</p></div><img className="studio-cube" src={buddyAssets.buddy} decoding="async" alt="Carve mascot holding an onchain crystal" width="512" height="512"/></div>
 <div className="studio-grid"><div className="editor-column">
 <section className="panel identity-panel"><SectionTitle number="01" title="Give it an identity"/><div className="two-fields"><label>Token name<input maxLength={64} placeholder="Your next big idea" value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Ticker<div className="input-prefix"><span>$</span><input maxLength={12} placeholder="SYMBOL" value={draft.symbol} onChange={e=>update('symbol',e.target.value.replace(/[^a-z0-9]/gi,'').toUpperCase())}/></div></label></div><label>Description <span className="optional">Optional · saved in this draft</span><textarea rows={2} maxLength={240} placeholder="What makes this token yours?" value={draft.description} onChange={e=>update('description',e.target.value)}/></label><div className="field-meta">{draft.description.length}/240</div></section>
 <section className="panel media-panel"><SectionTitle number="02" title="Make your mark" description="Choose any one, any two, or all three. Add at least one file; every selected file is inscribed."/><div className="asset-editors-stack">{(['image','audio','website'] as AssetKind[]).map(kind=><AssetEditor key={kind} kind={kind} asset={draft.assets[kind]} onChange={a=>{const assets={...currentDraft.current.assets};if(a)assets[kind]=a;else delete assets[kind];const next={...currentDraft.current,assets,updatedAt:Date.now()};currentDraft.current=next;setDraft(next);}}/>)}</div><div className="capsule-studio-link"><a href="#/agents">{draft.assets.website&&readCapsuleHTML(draft.assets.website.bytes)?'Agent capsule prepared · inspect or edit →':'Add an agent capsule →'}</a><p>Preserve a public blueprint or a real Musebook snapshot through the website inscription. Not a running AI.</p></div></section>
 {DEPLOYMENT.curveVersion===5&&<section className={'panel buyback-option '+(draft.autoBuyback?'enabled':'')}><div className="eyebrow">OPTIONAL · TRADE-TRIGGERED</div><button type="button" role="switch" aria-checked={draft.autoBuyback===true} className="buyback-switch" onClick={()=>update('autoBuyback',!draft.autoBuyback)}><span><strong>Automatic buyback & burn</strong><small>Put your token’s creator fees to work</small></span><span className="buyback-switch-state">{draft.autoBuyback?'ON':'OFF'}<span className="switch-track"><span/></span></span></button><div className="buyback-split"><span><strong>80%</strong> buyback & burn</span><span><strong>20%</strong> creator revenue</span></div><p>The other 20% remains your creator revenue. Carve’s separate 1% is unchanged. Set your creator fee below. This choice cannot change after launch.</p>{draft.autoBuyback&&<p className="muted">With a 1% creator fee: 0.2% creator revenue + 0.8% buyback budget. Buys and sells trigger processing once the minimum budget is reached; no trades means no processing. Tokens are sent to the dead address. Eligible trades pay extra gas.</p>}</section>}
 <section className="panel launch-panel"><SectionTitle number="03" title="Set up your launch"/>{[4,5].includes(DEPLOYMENT.curveVersion||0)?<><p><strong>1% Carve trading fee.</strong> Set an optional additional fee for your creator wallet. Normal fees apply from launch.</p><label>Creator trading fee <span className="optional">0–10%</span><div className="input-suffix"><input inputMode="decimal" placeholder="0" value={draft.creatorFee} onChange={e=>update('creatorFee',e.target.value)}/><span>%</span></div></label></>:<p><strong>1% total pool trading fee.</strong> No additional creator trading fee. Carve receives fees collected by its permanently locked launch position.</p>}{DEPLOYMENT.kind==='v3'&&Number(draft.creatorFee||'0')!==0&&<div className="warning"><p>This draft contains the previous {draft.creatorFee}% creator-fee setting, which the new pool design does not support.</p><button className="secondary" onClick={()=>update('creatorFee','0')}>Clear previous creator fee</button></div>}<label>Initial buy <span className="optional">Optional</span><div className="input-suffix"><input inputMode="decimal" placeholder="0.00" value={draft.initialBuy} onChange={e=>update('initialBuy',e.target.value)}/><span>ETH</span></div></label><p className="muted">{[4,5].includes(DEPLOYMENT.curveVersion||0)?'Choose any initial buy, including zero. The curve starts with 1 billion tokens and a 1.68 ETH virtual reserve; virtual ETH is pricing only, not deposited liquidity. At 4.2 ETH of real reserve, the contract migrates liquidity to Uniswap V4 and locks it permanently. Any excess initial buy is returned.':'The same transaction creates and funds the locked Uniswap pool with tokens, then executes your initial buy. Buyer ETH adds the ETH side; without a buy, the pool starts with token liquidity only. The 4.2 ETH principal milestone never changes the trading pool.'}</p></section>
 </div><aside className="preview-column"><div className="preview-sticky"><div className="preview-label"><span>YOUR INSCRIPTION</span><Status>LOCAL PREVIEW</Status></div><div className="token-preview"><div className="preview-art">{preview==='website'&&draft.assets.website?<iframe title="Token website preview" sandbox="allow-scripts" srcDoc={isolatedHtml(new TextDecoder().decode(draft.assets.website.bytes))}/>:preview!=='sample'&&url?<img className="token-image" src={url} alt={draft.name||'Your token artwork'}/>:<div className="brand-art"><picture className="buddy-hello-preview"><source media="(prefers-reduced-motion: reduce)" srcSet={sampleGifStillURL}/><img className="sample-gif" src={sampleGifURL} alt="Carve Buddy waving hello — sample animation" width="256" height="256" loading="lazy" decoding="async"/></picture><span className="art-caption">SAMPLE GIF · NOT INCLUDED IN YOUR LAUNCH</span></div>}<div className="preview-controls"><button aria-pressed={preview==='image'} onClick={()=>setPreview('image')}><FileImage size={15}/>Image</button><button aria-pressed={preview==='website'} disabled={!draft.assets.website} onClick={()=>setPreview('website')}><Globe size={15}/>Website</button><button aria-pressed={preview==='sample'} onClick={()=>setPreview('sample')}>GIF demo</button></div></div><div className="token-caption"><div><h2>{draft.name||'Your creation'}</h2><span>${draft.symbol||'TICKER'}</span></div><span className="token-chain"><img src="/brand/carve-mascot-96.png" alt="" width={17} height={17}/>4663</span></div>{draft.description&&<p className="token-description">{draft.description}</p>}{audio&&<div className="token-audio"><AudioLines size={17}/><audio controls src={audio} preload="metadata"/></div>}<div className="media-status">{(['image','audio','website'] as AssetKind[]).map(k=><span className={draft.assets[k]?'ready':''} key={k}>{draft.assets[k]?<Check size={13}/>:<span>+</span>} {k==='audio'?'Sound':k[0].toUpperCase()+k.slice(1)}</span>)}</div></div>
 <section className="inscription-summary"><div className="summary-title"><ShieldCheck size={17}/><h3>Storage plan</h3></div><dl><div><dt>Prepared size</dt><dd>{bytesLabel(plan.bytes)}</dd></div><div><dt>Onchain chunks</dt><dd>{plan.chunks||'—'}</dd></div><div><dt>Storage location</dt><dd>Contract bytecode</dd></div></dl><p>Files are local until you approve verified upload transactions. No IPFS dependency.</p><Review draft={draft}/><span className="saved-status"><Check size={13}/>{saved}</span></section>
 <div className="subtle-note"><Info size={15}/><span>Published content is permanent. Review files and transaction costs before approving.</span></div></div></aside></div></>;
}
