import {useEffect,useMemo,useRef,useState} from 'react';
import {formatEther,zeroHash,type Address,type Hex} from 'viem';
import {ArrowUpRight} from 'lucide-react';
import {client,DEPLOYMENT,TOKEN_ABI,short} from '../lib/chain';
import {V3_FACTORY_ABI} from '../lib/v3-contracts';
import {readV3Market} from '../lib/v3-trading';
import {sharedReads,v3LifetimeVolume} from '../lib/v3-feed-data';
import {feedWindow,mergeFeed} from '../lib/feed-window';
import {filterLaunchFeed,DEFAULT_LAUNCH_FEED_OPTIONS,type LaunchFeedRow,type LaunchFeedOptions} from '../lib/launch-feed';
import {TokenThumbnail} from './TokenThumbnail';
type Row=LaunchFeedRow&{imageRoot:Hex;block:bigint;note:string};
function eth(v:bigint|null){if(v===null)return 'Unavailable';if(v>0n&&v<1000000000000n)return '<0.000001 ETH';return formatEther(v).replace(/(\.\d{0,6})\d*$/,'$1').replace(/\.0+$/,'')+' ETH';}
export function V3LaunchFeed({creator}:{creator?:Address}){
 const [rows,setRows]=useState<Row[]>([]),[filters,setFilters]=useState<LaunchFeedOptions>({...DEFAULT_LAUNCH_FEED_OPTIONS}),[live,setLive]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[info,setInfo]=useState({total:0n,cursor:null as bigint|null,updated:0}),revision=useRef(0),inflight=useRef(false),state=useRef(info);
 const visible=useMemo(()=>filterLaunchFeed(rows,filters),[rows,filters]);
 const load=async(mode:'initial'|'poll'|'more'|'manual'='poll')=>{if(inflight.current)return;inflight.current=true;const run=++revision.current;
  try{if(!DEPLOYMENT.factory||!DEPLOYMENT.registry||!DEPLOYMENT.deployedBlock)return;
   const count=await client.readContract({address:DEPLOYMENT.factory,abi:V3_FACTORY_ABI,functionName:'tokenCount'});
   if(mode==='poll'&&count===state.current.total&&Date.now()-state.current.updated<20000)return;
   setBusy(true);setError('');const read=sharedReads(client),block=await read.getBlockNumber(),total=await read.readContract({address:DEPLOYMENT.factory,abi:V3_FACTORY_ABI,functionName:'tokenCount',blockNumber:block});
   const page=feedWindow(total,mode==='more'&&state.current.cursor!==null&&state.current.cursor<=total?state.current.cursor:null);
   const fetched=await Promise.all(page.indices.map(async (index):Promise<Row|undefined>=>{
    const token=await read.readContract({address:DEPLOYMENT.factory!,abi:V3_FACTORY_ABI,functionName:'tokens',args:[index],blockNumber:block});
    const owner=await read.readContract({address:token,abi:TOKEN_ABI,functionName:'creator',blockNumber:block});if(creator&&owner.toLowerCase()!==creator.toLowerCase())return;
    const snapshot=await readV3Market(read,token,DEPLOYMENT,block),[name,symbol,image,audio,website]=await Promise.all([
     read.readContract({address:token,abi:TOKEN_ABI,functionName:'name',blockNumber:block}),read.readContract({address:token,abi:TOKEN_ABI,functionName:'symbol',blockNumber:block}),
     ...(['imageRoot','audioRoot','websiteRoot'] as const).map(functionName=>read.readContract({address:token,abi:TOKEN_ABI,functionName,blockNumber:block})),
    ]);
    const volume=await v3LifetimeVolume(read,snapshot.pool,!snapshot.tokenIs0,BigInt(DEPLOYMENT.deployedBlock!),block),rawProgress=snapshot.wethPrincipal*100000000n/4200000000000000000n,progress=Number(rawProgress>100000000n?100000000n:rawProgress)/10000;
    return{index,token,market:snapshot.pool,creator:owner,name,symbol,phase:snapshot.milestoneReached?4:3,reserve:snapshot.wethPrincipal,marketCapETH:snapshot.fdvETHWei,volumeETH:volume.wei,curveProgressBps:progress,creatorFee:0,hasImage:image!==zeroHash,hasAudio:audio!==zeroHash,hasWebsite:website!==zeroHash,imageRoot:image as Hex,block,note:volume.note} satisfies Row;
   }));
   if(revision.current===run){const old=state.current,next={total,cursor:(mode==='initial'||mode==='more')||old.cursor===null||old.cursor>total||total-old.total>12n?page.cursor:old.cursor,updated:Date.now()};state.current=next;setInfo(next);setRows(previous=>mode==='initial'?fetched.filter((r):r is Row=>!!r):mergeFeed(previous,fetched.filter((r):r is Row=>!!r),total));}
  }catch(e){if(revision.current===run)setError((e as Error).message);}finally{if(revision.current===run){inflight.current=false;setBusy(false);}}
 };
 const loader=useRef(load);loader.current=load;
 useEffect(()=>{revision.current++;inflight.current=false;setRows([]);state.current={total:0n,cursor:null,updated:0};setInfo(state.current);void loader.current('initial');return()=>{revision.current++;};},[creator]);
 useEffect(()=>{if(!live)return;const poll=()=>{if(document.visibilityState==='visible')void loader.current('poll');};const id=setInterval(poll,5000);document.addEventListener('visibilitychange',poll);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',poll);};},[live,creator]);
 const set=<K extends keyof LaunchFeedOptions>(k:K,v:LaunchFeedOptions[K])=>setFilters(old=>({...old,[k]:v}));
 return <section className="panel feed-panel"><div className="feed-heading"><div><h2>{creator?'Your onchain launches':'Recent launches'}</h2><p className="feed-updated">{info.updated?'Updated '+new Date(info.updated).toLocaleTimeString():'Reading Robinhood Chain'}</p></div><div className="feed-live-controls"><label><input type="checkbox" checked={live} onChange={e=>setLive(e.target.checked)}/>{live?'Live updates':'Updates paused'}</label><button className="text-link" disabled={busy} onClick={()=>load('manual')}>Refresh</button></div></div>
 <div className="feed-filters"><label className="feed-search">Search launches<input placeholder="Name, ticker, token or creator address" value={filters.search} onChange={e=>set('search',e.target.value)}/></label><label>Liquidity milestone<select value={filters.phase} onChange={e=>set('phase',e.target.value as LaunchFeedOptions['phase'])}><option value="all">All pools</option><option value="v3-building">Below 4.2 ETH</option><option value="v3-milestone">Milestone reached</option></select></label><label>Inscription<select value={filters.media} onChange={e=>set('media',e.target.value as LaunchFeedOptions['media'])}><option value="all">Any media</option><option value="image">Image</option><option value="audio">Sound</option><option value="website">Website</option><option value="complete">All three</option></select></label><label>Sort by<select value={filters.sort} onChange={e=>set('sort',e.target.value as LaunchFeedOptions['sort'])}>{[['newest','Newest'],['oldest','Oldest'],['marketcap-desc','Market cap: high to low'],['marketcap-asc','Market cap: low to high'],['volume-desc','Volume: high to low'],['volume-asc','Volume: low to high'],['progress-desc','Milestone: high to low'],['progress-asc','Milestone: low to high'],['name','Name A–Z']].map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label></div>
 <div className="feed-summary"><p>{visible.length} shown · {rows.length} loaded · {info.total.toString()} total. Filters apply to loaded launches.</p><button className="text-link" onClick={()=>setFilters({...DEFAULT_LAUNCH_FEED_OPTIONS})}>Reset filters</button></div>
 <div className="launch-list launch-grid">{visible.map(row=><a href={'#/explore?token='+row.token} key={row.token} className="launch-card market-card"><div className="market-card-top"><TokenThumbnail registry={DEPLOYMENT.registry!} root={row.imageRoot} name={row.name} audio={row.hasAudio} website={row.hasWebsite}/><div className="market-identity"><strong>{row.name}</strong><span className="market-ticker">${row.symbol}</span><code>{short(row.token)}</code></div><ArrowUpRight size={18}/></div><div className="market-stage"><span className="status-tag">UNISWAP V3</span><span>1% pool fee · locked liquidity</span></div><dl className="market-numbers"><div><dt>Market cap / FDV</dt><dd>{eth(row.marketCapETH)}</dd></div><div><dt>Lifetime pool volume</dt><dd>{eth(row.volumeETH)}</dd></div><div><dt>Liquidity milestone</dt><dd>{((row.curveProgressBps||0)/100).toLocaleString(undefined,{maximumFractionDigits:6})}%</dd></div></dl><progress max={10000} value={row.curveProgressBps||0} aria-label={row.symbol+' liquidity milestone'}/><div className="market-card-bottom"><span>{[row.hasImage?'Image':'',row.hasAudio?'Sound':'',row.hasWebsite?'Website':''].filter(Boolean).join(' · ')}</span><span>{eth(row.reserve)} / 4.2 ETH</span></div><small>Read at block {row.block.toString()}{row.note?' · '+row.note:''}</small></a>)}</div>
 {!visible.length&&!busy&&!error&&<p>{rows.length?'No launches match these filters.':info.total===0n?'No tokens have launched on the new public-pool factory yet.':'No matching launches in this page. Load older launches below.'}</p>}{busy&&<p role="status">Checking registered pools and onchain figures…</p>}{error&&<p className="error" role="alert">{error} Existing figures retain their labelled block snapshots.</p>}{info.cursor!==null&&info.cursor>0n&&<button className="secondary" disabled={busy} onClick={()=>load('more')}>Load older launches</button>}
 <p className="muted">New launches are checked every 5 seconds; recent figures refresh every 20 seconds while visible. Values are in ETH. Market cap is fully diluted supply × spot price, not a sale quote. Volume counts the WETH side of verified pool swaps, including the input fee on buys. The 4.2 ETH current-principal milestone can reverse; the pool never migrates. Older cards keep labelled snapshots.</p></section>;
}
