import {useEffect,useRef,useState} from 'react';
import {formatEther,parseEther,parseUnits,type Address} from 'viem';
import {ArrowDownUp,ArrowUpRight} from 'lucide-react';
import {client,V3_DEPLOYMENT as DEPLOYMENT,TOKEN_ABI} from '../lib/chain';
import {V3_FACTORY_ABI,V3_CANONICAL} from '../lib/v3-contracts';
import {readV3Market,quoteV3,executeV3,unwrapWETH,type V3Quote,type V3Snapshot} from '../lib/v3-trading';
import {sendChecked,type Progress} from '../lib/transactions';
import {useTransactionSession} from './LaunchAction';
import {WalletDialog} from './WalletDialog';

export function V3TokenTrading({token,symbol}:{token:Address;symbol:string}){
 const [snapshot,setSnapshot]=useState<V3Snapshot|null>(null),[buy,setBuy]=useState(true),[amount,setAmount]=useState(''),[slippage,setSlippage]=useState('0.5'),[quote,setQuote]=useState<V3Quote|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState<Progress|null>(null),[weth,setWeth]=useState(0n),[credit,setCredit]=useState(0n),[assetBalance,setAssetBalance]=useState(0n);
 const {w,getSession}=useTransactionSession(setProgress,DEPLOYMENT),revision=useRef(0),alive=useRef(true),reading=useRef(false);
 const key=token+':'+w.address+':'+w.chainId,current=useRef(key);current.current=key;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;revision.current++;};},[]);
 const refresh=async()=>{if(reading.current)return;reading.current=true;const run=++revision.current,identity=key;try{
  const state=await readV3Market(client,token,DEPLOYMENT),[balance,pending,asset]=w.address?await Promise.all([
   client.readContract({address:V3_CANONICAL.weth,abi:TOKEN_ABI,functionName:'balanceOf',args:[w.address]}),
   client.readContract({address:DEPLOYMENT.factory!,abi:V3_FACTORY_ABI,functionName:'pendingETH',args:[w.address]}),
   buy?client.getBalance({address:w.address}):client.readContract({address:token,abi:TOKEN_ABI,functionName:'balanceOf',args:[w.address]}),
  ]):[0n,0n,0n];
  if(alive.current&&current.current===identity&&revision.current===run){setSnapshot(state);setWeth(balance);setCredit(pending);setAssetBalance(asset);}
 }finally{reading.current=false;}};
 const refreshRef=useRef(refresh);refreshRef.current=refresh;
 useEffect(()=>{revision.current++;reading.current=false;setSnapshot(null);setQuote(null);setError('');setWeth(0n);setCredit(0n);setAssetBalance(0n);void refreshRef.current().catch(e=>{if(alive.current&&current.current===key)setError((e as Error).message);});return()=>{revision.current++;};},[key,buy]);
 const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');const identity=key;try{await fn();if(alive.current&&current.current===identity)await refreshRef.current();}catch(e){if(alive.current&&current.current===identity)setError((e as Error).message);}finally{if(alive.current)setBusy(false);}};
 const validWallet=!!w.address&&w.chainId===4663&&DEPLOYMENT.launchEnabled;
 const bps=()=>{if(!/^(?:[0-4](?:\.\d{1,2})?|5(?:\.0{1,2})?)$/.test(slippage))throw new Error('Enter slippage from 0% to 5%.');return Number(parseUnits(slippage,2));};
 const setPercent=(percent:number)=>{if(assetBalance===0n)return;setAmount(formatEther(assetBalance*BigInt(percent)/100n));setQuote(null);};
 const flip=()=>{setBuy(v=>!v);setAmount('');setQuote(null);};
 return <section className="panel token-trading"><div className="feed-heading"><div><h2>Trade ${symbol}</h2><p className="trade-subtitle">Market order · public token/WETH pool</p></div><span className="status-tag">POOL · 1%</span></div>
 {snapshot&&<p className="muted">Locked WETH principal: {formatEther(snapshot.wethPrincipal)} / 4.2 ETH · {snapshot.milestoneReached?'Milestone currently reached':'Building liquidity'}. Read at block {snapshot.block.toString()}.</p>}
 <div className="trade-shell"><div className="trade-mode"><span>Market swap</span><span>1% pool fee</span></div><label className="swap-field"><span>{buy?'You pay':'You sell'}</span><div><input aria-label={buy?'ETH to spend':symbol+' to sell'} placeholder="0.0" inputMode="decimal" disabled={busy} value={amount} onChange={e=>{setAmount(e.target.value);setQuote(null);}}/><strong>{buy?'ETH':symbol}</strong></div><small>{w.address?'Available: '+formatEther(assetBalance)+' '+(buy?'ETH':symbol):'Connect wallet to see balance'}</small></label><div className="quick-percentages" aria-label="Quick amount"><button disabled={busy||assetBalance===0n} onClick={()=>setPercent(25)}>25%</button><button disabled={busy||assetBalance===0n} onClick={()=>setPercent(50)}>50%</button><button disabled={busy||assetBalance===0n} onClick={()=>setPercent(75)}>75%</button><button disabled={busy||assetBalance===0n} onClick={()=>setPercent(100)}>Max</button></div><button className="swap-flip" aria-label="Flip swap direction" disabled={busy} onClick={flip}><ArrowDownUp size={17}/></button><label className="swap-field"><span>{buy?'You receive':'You receive'}</span><div><output>{quote?formatEther(quote.amountOut):'—'}</output><strong>{buy?symbol:'WETH'}</strong></div><small>{quote?'Quote expires in 60 seconds':'Get a quote to see estimated output'}</small></label><label className="slippage-row">Slippage <input aria-label="Slippage percent" inputMode="decimal" disabled={busy} value={slippage} onChange={e=>setSlippage(e.target.value)}/><span>%</span></label></div>
 <button className="secondary full" disabled={busy||!snapshot} onClick={()=>action(async()=>{if(!/^\d+(\.\d{1,18})?$/.test(amount))throw new Error('Enter a positive amount.');bps();const q=await quoteV3(client,token,buy,parseEther(amount),DEPLOYMENT);if(alive.current&&current.current===key)setQuote(q);})}>{busy?'Checking…':'Preview swap'}</button>
 {quote&&<div className="transaction-status"><p>Estimated output: <strong>{formatEther(quote.amountOut)} {buy?symbol:'WETH'}</strong></p><p>Includes the 1% pool fee. Quote block {quote.snapshot.block.toString()}; expires after 60 seconds.</p>{!buy&&<p>WETH goes directly to your wallet. Use Unwrap below to convert it to ETH.</p>}{!w.address?<WalletDialog/>:w.chainId!==4663?<button className="secondary full" onClick={()=>w.switchChain()}>Switch to Robinhood Chain</button>:<button className="primary full" disabled={busy||!validWallet} onClick={()=>action(async()=>{const result=await executeV3(getSession(),quote,bps());setProgress({message:'Trade confirmed: '+formatEther(result.amountOut)+' '+(quote.buy?symbol:'WETH')+' received.',hash:result.transactionHash});setQuote(null);})}>Review {buy?'buy':'sell'} in wallet</button>}</div>}
 {weth>0n&&<div className="credit-row"><span>WETH in your wallet<strong>{formatEther(weth)} WETH</strong></span><button className="secondary" disabled={busy||!validWallet} onClick={()=>action(async()=>{const receipt=await unwrapWETH(getSession(),weth);setProgress({message:'Your WETH was unwrapped to ETH.',hash:receipt.transactionHash});})}>Unwrap to ETH</button></div>}
 {credit>0n&&<div className="credit-row"><span>Launch refund / creation-fee credit<strong>{formatEther(credit)} ETH</strong></span><button className="secondary" disabled={busy||!validWallet} onClick={()=>action(()=>sendChecked(getSession(),{address:DEPLOYMENT.factory!,abi:V3_FACTORY_ABI,functionName:'withdrawETH',args:[w.address!]}))}>Withdraw ETH</button></div>}
 {progress&&<p role="status">{progress.message} {progress.hash&&<a href={'https://robinhoodchain.blockscout.com/tx/'+progress.hash} target="_blank" rel="noreferrer">Transaction ↗</a>}</p>}{error&&<p className="error" role="alert">{error}</p>}
 <div className="button-row"><button className="text-link" disabled={busy} onClick={()=>action(refreshRef.current)}>Refresh balances</button><a href={'https://gmgn.ai/robinhood/token/'+token} target="_blank" rel="noreferrer">Open in GMGN <ArrowUpRight size={14}/></a>{snapshot&&<a href={'https://robinhoodchain.blockscout.com/address/'+snapshot.pool} target="_blank" rel="noreferrer">Public pool <ArrowUpRight size={14}/></a>}</div><p className="muted">External apps index pools independently. A sale may require a token approval first. Wallet and network checks run before each request; quotes do not guarantee a fill.</p></section>;
}
