import {lazy,Suspense,useEffect,useRef,useState,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowRight,ArrowUpRight,AudioLines,BookOpen,Check,Code2,Download,FileImage,Globe,Info,Layers,LoaderCircle,LockKeyhole,Menu,Search,ShieldCheck,Upload,Wallet,X} from 'lucide-react';
import {formatEther} from 'viem';
import {AssetEditor,useAssetUrl} from './components/AssetEditor';
import {WalletDialog} from './components/WalletDialog';
import {WalletProvider,useWallet} from './lib/wallet';
import {bytesLabel,download,exportDraft,importDraft,isolatedHtml,newDraft,planAssets,validateDraft,type AssetKind,type Draft} from './lib/assets';
import {loadDraft,saveLocal} from './lib/storage';
import {client,DEPLOYMENT,short,verifiedChain} from './lib/chain';
import {sampleGifURL} from './lib/sample-gif';
import {v3LaunchPlan} from './lib/v3-launch-plan';

import {LaunchAction} from './components/LaunchAction';
import {LaunchFeed} from './components/LaunchFeed';
const ExplorePage=lazy(()=>import('./components/ExplorePage').then(m=>({default:m.ExplorePage})));
const ProtocolPage=lazy(()=>import('./components/ProtocolPage').then(m=>({default:m.ProtocolPage})));
const DocsPage=lazy(()=>import('./components/DocsPage').then(m=>({default:m.DocsPage})));

type Route='home'|'studio'|'explore'|'library'|'protocol'|'docs';
const routes:{id:Route;label:string}[]=[{id:'home',label:'Home'},{id:'studio',label:'Create'},{id:'explore',label:'Explore'},{id:'library',label:'My workspace'},{id:'protocol',label:'How it works'},{id:'docs',label:'Docs'}];
function useRoute(){const read=()=>{const s=location.hash.slice(2).split('?')[0];return routes.some(r=>r.id===s)?s as Route:'home';};const [route,setRoute]=useState<Route>(read);useEffect(()=>{const h=()=>{setRoute(read());window.scrollTo({top:0,behavior:'instant'});};window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h);},[]);return route;}
function Brand(){return <a className="brand brand-cube" href="#/home" aria-label="Carve home"><img src="/brand/carve-mascot-96.png" alt="" width="48" height="48"/><span>CARVE</span></a>;}
function CarveEnvironment(){return <div className="carve-environment emerald-environment" aria-hidden="true"/>;}
function Status({children}:{children:ReactNode}){return <span className="status-tag">{children}</span>;}
function SectionTitle({number,title,description}:{number:string;title:string;description?:string}){return <div className="section-title"><span className="section-number">{number}</span><div><h2>{title}</h2>{description&&<p>{description}</p>}</div></div>;}

function Home(){return <><section className="home-hero"><div className="home-copy"><div className="eyebrow">CARVE / ON ROBINHOOD CHAIN</div><h1>Make the token<br/><em>the artifact.</em></h1><p>Carve lets creators launch a tradable token with its image, sound, and website stored as permanent onchain media—not a temporary hosted link.</p><div className="home-actions"><a className="primary" href="#/studio">Create a token <ArrowRight size={17}/></a><a className="secondary" href="#/explore">Explore launches <ArrowUpRight size={16}/></a></div><div className="home-note"><ShieldCheck size={16}/><span>Inspect each inscription directly from its onchain bytecode.</span></div></div><div className="home-visual"><img className="home-poster" src="/brand/carve-data-integrity.png" alt="Carve onchain data integrity poster showing image, sound and website inscriptions"/><div className="home-visual-label"><span>CREATIVE RECORD</span><strong>IMAGE · SOUND · WEBSITE</strong></div></div></section><section className="home-explainer"><article className="panel"><FileImage size={21}/><h2>1. Prepare your identity</h2><p>Choose an image, sound, website—or any combination. Each token needs at least one original creative file.</p></article><article className="panel"><Code2 size={21}/><h2>2. Inscribe it permanently</h2><p>Carve stores your selected file bytes in immutable contract bytecode, with manifests and chunk hashes to verify them.</p></article><article className="panel"><Search size={21}/><h2>3. Launch and inspect</h2><p>Your token opens in its own trading page. Anyone can reconstruct the stored files and inspect the same evidence.</p></article></section><section className="panel home-proof"><div><div className="eyebrow">NO BLACK BOX</div><h2>Built to be checked.</h2><p>Use Explore to read a token’s contract, rebuild its inscribed files, view the market state, and trade with a wallet you control.</p></div><div className="home-proof-actions"><a className="secondary" href="#/docs">Read verification docs <ArrowUpRight size={16}/></a><a className="text-link" href="#/protocol">How Carve works <ArrowRight size={15}/></a></div></section></>;}

function Review({draft}:{draft:Draft}){
 const [open,setOpen]=useState(false),w=useWallet(),plan=v3LaunchPlan(draft),issues=validateDraft(draft);
 return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className="primary full">Review inscription <ArrowRight size={18}/></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content review-dialog"><Dialog.Title>Review your inscription</Dialog.Title><Dialog.Description>Check your prepared files before any permanent onchain upload.</Dialog.Description><Dialog.Close className="icon-button dialog-close" aria-label="Close review"><X/></Dialog.Close>
 <dl className="review-details"><div><dt>Token</dt><dd>{draft.name||'Name needed'} · ${draft.symbol||'TICKER'}</dd></div><div><dt>Network</dt><dd>Robinhood Chain · 4663</dd></div><div><dt>Prepared media</dt><dd>{plan.files} files · {bytesLabel(plan.bytes)}</dd></div><div><dt>Wallet approvals</dt><dd>{plan.inline?([4,5].includes(DEPLOYMENT.curveVersion||0)?'1 · media + token + curve':'1 · media + token + pool'):`Up to ${plan.transactions} · resumable uploads`}</dd></div><div><dt>Initial buy</dt><dd>{draft.initialBuy||'0'} ETH</dd></div><div><dt>Connected wallet</dt><dd>{w.address?short(w.address):'Not connected'}</dd></div><div><dt>Launch fee</dt><dd>0.0005 ETH + storage & transaction gas</dd></div></dl>
 {issues.length>0&&<div className="warning"><strong>Still needed</strong><ul>{issues.map(x=><li key={x}>{x}</li>)}</ul></div>}
 <LaunchAction key={w.address+':'+w.selected?.info.uuid+':'+w.chainId} draft={draft}/>
 <button className="primary full" onClick={()=>download((draft.symbol||'carve')+'-draft.json',exportDraft(draft))}><Download size={17}/>Download prepared draft</button>
 <p className="muted">Published bytes are permanent. Only upload media you have permission to use. Confirmed chunks are reused when you resume the same draft.</p>
 </Dialog.Content></Dialog.Portal></Dialog.Root>;
}

function Studio({draft,setDraft,saved}:{draft:Draft;setDraft:(d:Draft)=>void;saved:string}){
 const currentDraft=useRef(draft);currentDraft.current=draft;
 const [preview,setPreview]=useState<'image'|'website'|'sample'>('image');const plan=planAssets(draft.assets),url=useAssetUrl(draft.assets.image),audio=useAssetUrl(draft.assets.audio);
 const update=(key:keyof Draft,value:string|boolean)=>setDraft({...draft,[key]:value,updatedAt:Date.now()});
 return <><div className="page-heading studio-heading"><div><div className="eyebrow">CARVE / ON ROBINHOOD CHAIN</div><h1>Launch tokens.<br/><em>Preserve creativity.</em></h1><p>Images. Sound. Websites. Permanently onchain.</p></div><img className="studio-cube" src="/brand/carve-mascot-512.png" srcSet="/brand/carve-mascot-256.png 256w, /brand/carve-mascot-512.png 512w" sizes="(max-width: 700px) 120px, 240px" alt="Carve mascot holding an onchain crystal" width="512" height="512"/></div>
 <div className="studio-grid"><div className="editor-column">
 <section className="panel identity-panel"><SectionTitle number="01" title="Give it an identity"/><div className="two-fields"><label>Token name<input maxLength={64} placeholder="Your next big idea" value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Ticker<div className="input-prefix"><span>$</span><input maxLength={12} placeholder="SYMBOL" value={draft.symbol} onChange={e=>update('symbol',e.target.value.replace(/[^a-z0-9]/gi,'').toUpperCase())}/></div></label></div><label>Description <span className="optional">Optional · saved in this draft</span><textarea rows={2} maxLength={240} placeholder="What makes this token yours?" value={draft.description} onChange={e=>update('description',e.target.value)}/></label><div className="field-meta">{draft.description.length}/240</div></section>
 <section className="panel media-panel"><SectionTitle number="02" title="Make your mark" description="Choose any one, any two, or all three. Add at least one file; every selected file is inscribed."/><div className="asset-editors-stack">{(['image','audio','website'] as AssetKind[]).map(kind=><AssetEditor key={kind} kind={kind} asset={draft.assets[kind]} onChange={a=>{const assets={...currentDraft.current.assets};if(a)assets[kind]=a;else delete assets[kind];const next={...currentDraft.current,assets,updatedAt:Date.now()};currentDraft.current=next;setDraft(next);}}/>)}</div></section>
 {DEPLOYMENT.curveVersion===5&&<section className={'panel buyback-option '+(draft.autoBuyback?'enabled':'')}><div className="eyebrow">OPTIONAL · TRADE-TRIGGERED</div><button type="button" role="switch" aria-checked={draft.autoBuyback===true} className="buyback-switch" onClick={()=>update('autoBuyback',!draft.autoBuyback)}><span><strong>Automatic buyback & burn</strong><small>Put your token’s creator fees to work</small></span><span className="buyback-switch-state">{draft.autoBuyback?'ON':'OFF'}<span className="switch-track"><span/></span></span></button><div className="buyback-split"><span><strong>80%</strong> buyback & burn</span><span><strong>20%</strong> creator revenue</span></div><p>The other 20% remains your creator revenue. Carve’s separate 1% is unchanged. Set your creator fee below. This choice cannot change after launch.</p>{draft.autoBuyback&&<p className="muted">With a 1% creator fee: 0.2% creator revenue + 0.8% buyback budget. Buys and sells trigger processing once the minimum budget is reached; no trades means no processing. Tokens are sent to the dead address. Eligible trades pay extra gas.</p>}</section>}
 <section className="panel launch-panel"><SectionTitle number="03" title="Set up your launch"/>{[4,5].includes(DEPLOYMENT.curveVersion||0)?<><p><strong>1% Carve trading fee.</strong> Set an optional additional fee for your creator wallet. Normal fees apply from launch.</p><label>Creator trading fee <span className="optional">0–10%</span><div className="input-suffix"><input inputMode="decimal" placeholder="0" value={draft.creatorFee} onChange={e=>update('creatorFee',e.target.value)}/><span>%</span></div></label></>:<p><strong>1% total pool trading fee.</strong> No additional creator trading fee. Carve receives fees collected by its permanently locked launch position.</p>}{DEPLOYMENT.kind==='v3'&&Number(draft.creatorFee||'0')!==0&&<div className="warning"><p>This draft contains the previous {draft.creatorFee}% creator-fee setting, which the new pool design does not support.</p><button className="secondary" onClick={()=>update('creatorFee','0')}>Clear previous creator fee</button></div>}<label>Initial buy <span className="optional">Optional</span><div className="input-suffix"><input inputMode="decimal" placeholder="0.00" value={draft.initialBuy} onChange={e=>update('initialBuy',e.target.value)}/><span>ETH</span></div></label><p className="muted">{[4,5].includes(DEPLOYMENT.curveVersion||0)?'Choose any initial buy, including zero. The curve starts with 1 billion tokens and a 1.68 ETH virtual reserve; virtual ETH is pricing only, not deposited liquidity. At 4.2 ETH of real reserve, the contract migrates liquidity to Uniswap V4 and locks it permanently. Any excess initial buy is returned.':'The same transaction creates and funds the locked Uniswap pool with tokens, then executes your initial buy. Buyer ETH adds the ETH side; without a buy, the pool starts with token liquidity only. The 4.2 ETH principal milestone never changes the trading pool.'}</p></section>
 </div><aside className="preview-column"><div className="preview-sticky"><div className="preview-label"><span>YOUR INSCRIPTION</span><Status>LOCAL PREVIEW</Status></div><div className="token-preview"><div className="preview-art">{preview==='website'&&draft.assets.website?<iframe title="Token website preview" sandbox="allow-scripts" srcDoc={isolatedHtml(new TextDecoder().decode(draft.assets.website.bytes))}/>:preview!=='sample'&&url?<img className="token-image" src={url} alt={draft.name||'Your token artwork'}/>:<div className="brand-art"><img className="sample-gif" src={sampleGifURL} alt="Sample animated GIF: an emerald signal ripple" width="256" height="256"/><span className="art-caption">SAMPLE GIF · NOT INCLUDED IN YOUR LAUNCH</span></div>}<div className="preview-controls"><button aria-pressed={preview==='image'} onClick={()=>setPreview('image')}><FileImage size={15}/>Image</button><button aria-pressed={preview==='website'} disabled={!draft.assets.website} onClick={()=>setPreview('website')}><Globe size={15}/>Website</button><button aria-pressed={preview==='sample'} onClick={()=>setPreview('sample')}>GIF demo</button></div></div><div className="token-caption"><div><h2>{draft.name||'Your creation'}</h2><span>${draft.symbol||'TICKER'}</span></div><span className="token-chain"><img src="/brand/carve-mascot-96.png" alt="" width={17} height={17}/>4663</span></div>{draft.description&&<p className="token-description">{draft.description}</p>}{audio&&<div className="token-audio"><AudioLines size={17}/><audio controls src={audio} preload="metadata"/></div>}<div className="media-status">{(['image','audio','website'] as AssetKind[]).map(k=><span className={draft.assets[k]?'ready':''} key={k}>{draft.assets[k]?<Check size={13}/>:<span>+</span>} {k==='audio'?'Sound':k[0].toUpperCase()+k.slice(1)}</span>)}</div></div>
 <section className="inscription-summary"><div className="summary-title"><ShieldCheck size={17}/><h3>Storage plan</h3></div><dl><div><dt>Prepared size</dt><dd>{bytesLabel(plan.bytes)}</dd></div><div><dt>Onchain chunks</dt><dd>{plan.chunks||'—'}</dd></div><div><dt>Storage location</dt><dd>Contract bytecode</dd></div></dl><p>Files are local until you approve verified upload transactions. No IPFS dependency.</p><Review draft={draft}/><span className="saved-status"><Check size={13}/>{saved}</span></section>
 <div className="subtle-note"><Info size={15}/><span>Published content is permanent. Review files and transaction costs before approving.</span></div></div></aside></div></>;
}

function Library({draft,setDraft}:{draft:Draft;setDraft:(d:Draft)=>void}){
 const w=useWallet(),[balance,setBalance]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),file=useRef<HTMLInputElement>(null);const url=useAssetUrl(draft.assets.image);
 useEffect(()=>{let active=true;setBalance(null);setError('');if(w.address&&w.chainId===4663){setBusy(true);client.getBalance({address:w.address}).then(v=>{if(active)setBalance(formatEther(v));}).catch(()=>{if(active)setError('Balance could not be read. Reconnect to retry.');}).finally(()=>{if(active)setBusy(false);});}else setBusy(false);return()=>{active=false;};},[w.address,w.chainId]);
 return <><div className="page-heading compact"><div><div className="eyebrow">YOUR CREATIVE SPACE</div><h1>My workspace.</h1><p>Resume your draft or check the wallet connected to Carve.</p></div></div><div className="workspace-grid"><section className="panel"><SectionTitle number="01" title="Saved on this device"/><div className="draft-card">{url?<img src={url} alt="Draft artwork"/>:<div className="draft-icon"><FileImage size={27}/></div>}<div><h3>{draft.name||'Untitled inscription'}</h3><p>${draft.symbol||'TICKER'} · {bytesLabel(planAssets(draft.assets).bytes)}</p><Status>NOT PUBLISHED</Status></div></div><div className="button-row"><a className="primary" href="#/studio">Continue editing <ArrowRight size={16}/></a><button className="secondary" onClick={()=>download((draft.symbol||'carve')+'-draft.json',exportDraft(draft))}><Download size={16}/>Export</button></div><button className="text-link" onClick={()=>file.current?.click()}><Upload size={15}/>Import a Carve draft</button><input className="visually-hidden" aria-label="Import draft file" ref={file} type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{setDraft(await importDraft(await f.text()));location.hash='/studio';}catch(err){setError((err as Error).message);}e.target.value='';}}/><p className="muted">Drafts stay in this browser. Export a copy before clearing browser data or switching devices.</p></section><section className="panel"><SectionTitle number="02" title="Connected wallet"/>{w.address?<><code className="full-address">{w.address}</code><div className="balance"><span>Robinhood ETH balance</span><strong>{w.chainId!==4663?'Switch network':busy?'Reading…':balance===null?'Unavailable':Number(balance).toLocaleString(undefined,{maximumFractionDigits:6})+' ETH'}</strong></div><WalletDialog/></>:<div className="empty-small"><Wallet size={30}/><h3>Your wallet, your account</h3><p>Connect an extension to read your real balance. No demo holdings are assigned.</p><WalletDialog/></div>}{error&&<p className="error" role="alert">{error}</p>}</section></div>{w.address&&<LaunchFeed creator={w.address}/>}</>;
}

function Shell(){const route=useRoute(),[draft,setDraft]=useState<Draft>(newDraft),[loaded,setLoaded]=useState(false),[saved,setSaved]=useState('Loading local draft…'),[menu,setMenu]=useState(false),[chain,setChain]=useState<{block:bigint;gasPrice:bigint}|null>(null),[chainError,setChainError]=useState(false);const latest=useRef(draft);latest.current=draft;
 useEffect(()=>{let active=true;loadDraft().then(d=>{if(active){setDraft(d);setSaved('Saved on this device');}}).catch(()=>{if(active)setSaved('Browser storage unavailable · export a copy');}).finally(()=>{if(active)setLoaded(true);});return()=>{active=false;};},[]);
 useEffect(()=>{if(!loaded)return;setSaved('Saving draft…');const t=setTimeout(()=>{saveLocal('draft',draft).then(()=>setSaved('Saved on this device')).catch(()=>setSaved('Not saved · export a copy'));},450);return()=>clearTimeout(t);},[draft,loaded]);
 useEffect(()=>{let active=true;const check=()=>verifiedChain().then(c=>{if(active){setChain(c);setChainError(false);}}).catch(()=>{if(active){setChainError(true);setChain(null);}});check();const timer=setInterval(check,60000);return()=>{active=false;clearInterval(timer);};},[]);
 useEffect(()=>{setMenu(false);},[route]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(t:unknown,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const c=new AbortController();const tools=[{name:'read_carve_draft',description:'Read the local draft summary. Does not launch a token.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({name:latest.current.name,symbol:latest.current.symbol,files:Object.keys(latest.current.assets),issues:validateDraft(latest.current),published:false})},{name:'stage_carve_identity',description:'Update name and ticker in the local draft. Does not upload or spend funds.',inputSchema:{type:'object',properties:{name:{type:'string'},symbol:{type:'string'}},required:['name','symbol'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const v=input as {name:string;symbol:string};if(typeof v?.name!=='string'||typeof v?.symbol!=='string'||v.name.length>64||!/^[A-Za-z0-9]{1,12}$/.test(v.symbol))throw new Error('Name and ticker are invalid.');const next={...latest.current,name:v.name,symbol:v.symbol.toUpperCase(),updatedAt:Date.now()};latest.current=next;setDraft(next);return {name:next.name,symbol:next.symbol,staged:true,published:false};}}];for(const t of tools)try{Promise.resolve(context.registerTool(t,{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort();},[]);
 return <><a className="skip-link" href="#main">Skip to workspace</a><header className="site-header"><div className="header-inner"><Brand/><nav className={menu?'open':''} aria-label="Main navigation">{routes.map(r=><a href={'#/'+r.id} aria-current={route===r.id?'page':undefined} key={r.id}>{r.label}</a>)}</nav><div className="header-actions"><span className="network-label"><Layers size={14}/>Robinhood</span><WalletDialog/><button className="icon-button mobile-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
 {!DEPLOYMENT.launchEnabled&&<div className="preview-banner"><span className="preview-pill">DEPLOYMENT PENDING</span><p>Mainnet transactions unlock after the launchpad contracts are deployed and verified.</p><a href="#/protocol">Release status <ArrowUpRight size={13}/></a></div>}
 <main id="main" className="site-main"><Suspense fallback={<p role="status">Loading workspace…</p>}>{route==='home'?<Home/>:route==='studio'?<Studio draft={draft} setDraft={setDraft} saved={saved}/>:route==='explore'?<ExplorePage/>:route==='library'?<Library draft={draft} setDraft={setDraft}/>:route==='docs'?<DocsPage/>:<ProtocolPage/>}</Suspense></main><footer><Brand/><span>Not just a link. A lasting record.</span><a className="footer-link" href="https://github.com/Chief-codes/carve-robinhood" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13}/></a><div className={'chain-status '+(chainError?'offline':'')} title={chain?'Live RPC block '+chain.block:'Read-only connection'}><i/>{chain?'RH · BLOCK '+chain.block.toLocaleString():chainError?'RPC temporarily unavailable':'Connecting to chain…'}</div></footer></>;
}
export default function App(){return <WalletProvider><CarveEnvironment/><Shell/></WalletProvider>;}
