import {lazy,Suspense,useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowRight,ArrowUpRight,AudioLines,BookOpen,Check,Code2,Download,FileImage,Globe,Info,Layers,LoaderCircle,LockKeyhole,Menu,Search,ShieldCheck,Upload,Wallet,X} from 'lucide-react';
import {WalletDialog} from './components/WalletDialog';
import {WalletProvider,useWallet} from './lib/wallet';
import {newDraft,validateDraft,type Draft} from './lib/assets';
import {loadDraft,saveLocal} from './lib/storage';
import {DEPLOYMENT} from './lib/chain';
import './agents.css';

import {CarveIntroduction} from './components/CarveIntroduction';
import {CarveLaunchInvitation} from './components/CarveLaunchInvitation';
const Studio=lazy(()=>import('./components/StudioPage').then(m=>({default:m.Studio})));
const Library=lazy(()=>import('./components/LibraryPage').then(m=>({default:m.Library})));
const ExplorePage=lazy(()=>import('./components/ExplorePage').then(m=>({default:m.ExplorePage})));
const ProtocolPage=lazy(()=>import('./components/ProtocolPage').then(m=>({default:m.ProtocolPage})));
const DocsPage=lazy(()=>import('./components/DocsPage').then(m=>({default:m.DocsPage})));
const AgentCapsules=lazy(()=>import('./components/AgentCapsules').then(m=>({default:m.AgentCapsules})));

type Route='home'|'studio'|'explore'|'agents'|'library'|'protocol'|'docs';
const routes:{id:Route;label:string}[]=[{id:'home',label:'Home'},{id:'studio',label:'Create'},{id:'explore',label:'Explore'},{id:'agents',label:'Musebook'},{id:'library',label:'My workspace'},{id:'protocol',label:'How it works'},{id:'docs',label:'Docs'}];
function useRoute(){const read=()=>{const s=location.hash.slice(2).split('?')[0];return routes.some(r=>r.id===s)?s as Route:'home';};const [route,setRoute]=useState<Route>(read);useEffect(()=>{const h=()=>{setRoute(read());window.scrollTo({top:0,behavior:'instant'});};window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h);},[]);return route;}
function Brand(){return <a className="brand brand-cube" href="#/home" aria-label="Carve home"><img src="/brand/carve-mascot-96.png" alt="" width="48" height="48"/><span>CARVE</span></a>;}
function CarveEnvironment(){return <div className="carve-environment emerald-environment" aria-hidden="true"/>;}


function Home(){return <><CarveIntroduction/><CarveLaunchInvitation/><section id="meet-carve" className="home-story"><div><div className="eyebrow">MEET CARVE</div><h2>A token can be more than a ticker.</h2></div><p>Carve gives every launch a permanent creative identity. Your media is written into contract bytecode, so people can inspect it, reconstruct it, and keep it long after ordinary links disappear.</p></section><section className="home-explainer"><article className="panel"><FileImage size={21}/><h2>1. Create the identity</h2><p>Bring an image, a sound, a website—or all three. Every launch starts with something unmistakably yours.</p></article><article className="panel"><Code2 size={21}/><h2>2. Carve it onchain</h2><p>Your selected media is stored permanently in immutable contract bytecode with verifiable chunk hashes.</p></article><article className="panel"><Search size={21}/><h2>3. Launch and trade</h2><p>Open a transparent bonding curve, build the community, and graduate liquidity to Uniswap V4.</p></article></section><section className="panel home-proof"><div><div className="eyebrow">NO BLACK BOX</div><h2>Built to be checked.</h2><p>Use Explore to read a token’s contract, rebuild its inscribed files, view market state, and trade with a wallet you control.</p></div><div className="home-proof-actions"><a className="secondary" href="#/docs">Read verification docs <ArrowUpRight size={16}/></a><a className="text-link" href="#/protocol">How Carve works <ArrowRight size={15}/></a></div></section></>;}



function Shell(){const route=useRoute(),[draft,setDraft]=useState<Draft>(newDraft),[loaded,setLoaded]=useState(false),[saved,setSaved]=useState('Loading local draft…'),[menu,setMenu]=useState(false);const latest=useRef(draft);latest.current=draft;
 useEffect(()=>{let active=true;loadDraft().then(d=>{if(active){setDraft(d);setSaved('Saved on this device');}}).catch(()=>{if(active)setSaved('Browser storage unavailable · export a copy');}).finally(()=>{if(active)setLoaded(true);});return()=>{active=false;};},[]);
 useEffect(()=>{if(!loaded)return;setSaved('Saving draft…');const t=setTimeout(()=>{saveLocal('draft',draft).then(()=>setSaved('Saved on this device')).catch(()=>setSaved('Not saved · export a copy'));},450);return()=>clearTimeout(t);},[draft,loaded]);
 useLayoutEffect(()=>{setMenu(false);document.documentElement.dataset.carveTheme='light';},[route]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(t:unknown,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const c=new AbortController();const tools=[{name:'read_carve_draft',description:'Read the local draft summary. Does not launch a token.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({name:latest.current.name,symbol:latest.current.symbol,files:Object.keys(latest.current.assets),issues:validateDraft(latest.current),published:false})},{name:'stage_carve_identity',description:'Update name and ticker in the local draft. Does not upload or spend funds.',inputSchema:{type:'object',properties:{name:{type:'string'},symbol:{type:'string'}},required:['name','symbol'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const v=input as {name:string;symbol:string};if(typeof v?.name!=='string'||typeof v?.symbol!=='string'||v.name.length>64||!/^[A-Za-z0-9]{1,12}$/.test(v.symbol))throw new Error('Name and ticker are invalid.');const next={...latest.current,name:v.name,symbol:v.symbol.toUpperCase(),updatedAt:Date.now()};latest.current=next;setDraft(next);return {name:next.name,symbol:next.symbol,staged:true,published:false};}}];for(const t of tools)try{Promise.resolve(context.registerTool(t,{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort();},[]);
 return <><a className="skip-link" href="#main">Skip to workspace</a><header className="site-header"><div className="header-inner"><Brand/><nav className={menu?'open':''} aria-label="Main navigation">{routes.map(r=><a href={'#/'+r.id} aria-current={route===r.id?'page':undefined} key={r.id}>{r.label}</a>)}</nav><div className="header-actions"><span className="network-label"><Layers size={14}/>Robinhood</span><WalletDialog/><button className="icon-button mobile-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
 {!DEPLOYMENT.launchEnabled&&<div className="preview-banner"><span className="preview-pill">DEPLOYMENT PENDING</span><p>Mainnet transactions unlock after the launchpad contracts are deployed and verified.</p><a href="#/protocol">Release status <ArrowUpRight size={13}/></a></div>}
 <main id="main" className="site-main"><Suspense fallback={<p role="status">Loading workspace…</p>}>{route==='home'?<><Home/><section className="panel capsule-home-link"><div><div className="eyebrow">AGENT CAPSULES</div><h2>Preserve the identity. Keep the evidence.</h2><p>Create a public blueprint or archive a real Musebook conversation with your token.</p></div><a className="secondary" href="#/agents">Explore Musebook <ArrowRight size={16}/></a></section></>:route==='studio'?<Studio draft={draft} setDraft={setDraft} saved={saved}/>:route==='explore'?<ExplorePage/>:route==='agents'?<AgentCapsules draft={draft} setDraft={setDraft} ready={loaded}/>:route==='library'?<Library draft={draft} setDraft={setDraft}/>:route==='docs'?<DocsPage/>:<ProtocolPage/>}</Suspense></main><footer><Brand/><span>Not just a link. A lasting record.</span><a className="footer-link" href="https://github.com/Chief-codes/carve-robinhood" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13}/></a><a className="footer-link" href="https://x.com/CarveOnRh" target="_blank" rel="noopener noreferrer" aria-label="Carve on X">@CarveOnRh <ArrowUpRight size={13}/></a></footer></>;
}
export default function App(){return <WalletProvider><CarveEnvironment/><Shell/></WalletProvider>;}
