import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import {PageLoadBoundary} from './components/PageLoadBoundary';
import './styles.css';
import './brand.css';
import './buyback.css';
import './carve-theme.css';
document.documentElement.dataset.carveTheme='light';
createRoot(document.getElementById('root')!).render(<React.StrictMode><PageLoadBoundary><App /></PageLoadBoundary></React.StrictMode>);
